version: '3.7'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"'

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./monitoring-config/tempo-config.yml:/etc/tempo-config.yml
    command: --config.file=/etc/tempo-config.yml
    networks:
      - monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./monitoring-config/otel-collector-config.yml:/etc/otel/otel-collector-config.yml
    command: --config=/etc/otel/otel-collector-config.yml
    networks:
      - monitoring
    depends_on:
      - tempo

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./monitoring-config/loki-config.yml:/etc/loki/local-config.yml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring-config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=4d'
      - '--log.level=warn'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana


  snail-app-1:
    image: minseok1768/snail-app:latest
    container_name: snail-app-1
    env_file:
      - .env
    ports:
      - "8082:8080"
    restart: always
    networks:
      - monitoring

  snail-app-2:
    image: minseok1768/snail-app:latest
    container_name: snail-app-2
    env_file:
      - .env
    ports:
      - "8083:8080"
    restart: always
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - snail-app-1
      - snail-app-2
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
  influxdb-storage:
