auth_enabled: false

server:
  log_level: warn
  http_listen_port: 3200
  grpc_listen_port: 4318 # gRPC 요청을 수신하는 기본 포트

distributor: # OTLP(오픈텔레메트리 프로토콜) 수신을 위해 gRPC 서버를 띄우는 포트
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317 # OTLP gRPC 프로토콜을 통해 들어오는 데이터를 받기 위한 "리시버(receiver)"가 4317
        http:
          endpoint: 0.0.0.0:55681 # OTLP HTTP 프로토콜 수신 포트

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    retention_enabled: true
    retention_delete_delay: 24h
    retention_delete_interval: 1h
    retention: 140h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
    wal:
      path: /tmp/tempo/wal


querier: {}

query_frontend: {}

memberlist:
  join_members: ["127.0.0.1"]  # ring 구성에 필수

overrides:
  metrics_generator_processors: []